import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import Header from './components/Header';
import { Providers } from "./providers";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "cyrillic"],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Окна",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={roboto.variable}>
      <body className="font-sans antialiased bg-[#E5E5E5] text-primary-text">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
